### ISSUE TITLE
Not working on ForkCMS 3.7

### ISSUE THREAD

**Issue by Sellato** [bart-webleads/navigation-block#1]
Good day!
Can your convert this module for working with ForkCMS 3.7

Fatal error: Class 'ModuleInstaller' not found in J:\web\htdocs\forkcms.rup\src\Backend\Modules\navigation_block\installer\installer.php on line 16

Thanks

**Comment by bart-webleads** [comment]
I plan to convert it to 3.7, when I have the time...
